const CATEGORIES = [
  { name: "Windows", icon: "▣", blurb: "Fix common Windows issues and learn useful settings." },
  { name: "Linux", icon: "⌘", blurb: "Commands, troubleshooting and beginner-friendly Linux guides." },
  { name: "Networking", icon: "⌁", blurb: "Wi-Fi, DNS, IP and connectivity troubleshooting." },
  { name: "AI & Technology", icon: "✦", blurb: "Useful AI tools, tips and practical explainers." },
  { name: "IT Support", icon: "⚙", blurb: "Practical support workflows and troubleshooting." },
  { name: "Software & Tools", icon: "▤", blurb: "Guides to useful software and productivity tools." },
];

const ARTICLES = [
  {
    id: "network-troubleshooting",
    category: "Networking",
    title: "How to Troubleshoot a Network Connection: A Beginner's Guide",
    excerpt: "A simple process for checking cables, adapters, IP configuration, DNS and ping before you escalate a network issue.",
    readTime: 8,
    level: "Beginner",
    body: [
      { h: "Start with the physical layer", p: "Before touching any settings, confirm the cable is fully seated, the Wi-Fi network is the one you expect, and the adapter's link light is on. A surprising number of outages are solved by re-seating a cable or power-cycling the router." },
      { h: "Confirm the adapter is detected", p: "Your operating system needs to see the network adapter before anything else can work. Check Device Manager on Windows, System Settings on macOS, or run ip link show on Linux to confirm the interface is up." },
      { h: "Check your IP configuration", p: "Run ipconfig or ip addr. An address starting with 169.254 means the device never got a real address from the router — release and renew it, or reconnect to the network." },
      { h: "Separate DNS problems from connectivity problems", p: "Ping an IP address directly, then ping a domain name. If the IP works but the domain doesn't, DNS is the problem, not your connection. Switching to a public resolver like 1.1.1.1 often clears it up." },
      { h: "Trace the rest of the path", p: "If pinging your router fails, the fault is between you and it. If the router responds but nothing beyond it does, run a trace route to see exactly where the path breaks — and whether it's time to call your ISP." },
    ],
  },
  {
    id: "windows-boot-recovery",
    category: "Windows",
    title: "Windows Won't Boot? A Step-by-Step Recovery Checklist",
    excerpt: "From a black screen to a boot loop — a calm, ordered checklist for getting a Windows machine back to life.",
    readTime: 7,
    level: "Intermediate",
    body: [
      { h: "Don't panic, and don't reinstall yet", p: "Most boot failures are fixable without wiping the drive. Reinstalling should be the last resort, not the first troubleshooting step." },
      { h: "Get into the recovery environment", p: "Interrupt the boot process three times in a row (turning the PC off during startup) to force Windows Recovery Environment to load automatically, or boot from installation media." },
      { h: "Try Startup Repair first", p: "It's automated, safe, and fixes the most common causes: a corrupted boot configuration data (BCD) file or a damaged master boot record." },
      { h: "Roll back recent changes", p: "If the failure started right after a driver install or Windows update, use System Restore or Uninstall Updates from the recovery menu to undo the change that likely caused it." },
      { h: "Check the disk itself", p: "From the recovery command prompt, run chkdsk /f to repair file system errors and sfc /scannow to repair corrupted system files. Run these before assuming the drive has failed." },
      { h: "When to stop troubleshooting", p: "If chkdsk reports bad sectors it can't repair, or the drive isn't detected by BIOS at all, that points to hardware failure — back up what you can from recovery mode and plan for a replacement drive." },
    ],
  },
  {
    id: "linux-commands-beginners",
    category: "Linux",
    title: "10 Linux Commands Every IT Beginner Should Know",
    excerpt: "The small set of commands that cover most day-to-day troubleshooting on any Linux machine.",
    readTime: 6,
    level: "Beginner",
    body: [
      { h: "Move and look around", p: "pwd shows where you are, ls lists what's there, and cd moves you. Add ls -la to see hidden files and permissions in one view." },
      { h: "Read and search files", p: "cat prints a whole file, less lets you page through a long one, and grep searches inside files for a pattern." },
      { h: "Understand what's running", p: "ps aux lists every running process, and top (or htop, if installed) shows live CPU and memory usage so you can spot what's hogging resources." },
      { h: "Check disk and memory", p: "df -h shows disk space in human-readable form, and free -h shows memory usage. Both are usually the first thing to check when a system feels slow." },
      { h: "Manage permissions safely", p: "chmod changes what a file allows, and chown changes who owns it. Get comfortable with these before you reach for sudo out of habit." },
      { h: "Network basics", p: "ip addr shows your network configuration, and ping tests reachability. Between those two, you can diagnose most simple connectivity issues." },
    ],
  },
  {
    id: "how-llms-work",
    category: "AI & Technology",
    title: "How Large Language Models Actually Work, Explained Simply",
    excerpt: "No jargon, no hype — a plain explanation of what's happening when you type a prompt and get an answer back.",
    readTime: 9,
    level: "Beginner",
    body: [
      { h: "It starts with prediction, not understanding", p: "A language model is trained to predict the next word in a sequence, over and over, across enormous amounts of text. Everything it can do grows out of that one repeated task." },
      { h: "Text becomes numbers", p: "Your prompt is broken into small chunks called tokens, and each token is converted into a list of numbers the model can do math on. Words with related meanings end up with similar number patterns." },
      { h: "Attention decides what matters", p: "As the model processes your prompt, a mechanism called attention lets it weigh which earlier words are relevant to the word it's generating next." },
      { h: "Generation is one word at a time", p: "The model produces one token, adds it to the conversation, and repeats — using everything generated so far to inform the next token." },
      { h: "Why it can still be wrong", p: "Because the model is predicting plausible text rather than looking facts up, it can produce confident, fluent answers that are incorrect. Treat it as a capable assistant to verify, not an infallible source." },
    ],
  },
  {
    id: "writing-support-tickets",
    category: "IT Support",
    title: "How to Write a Support Ticket That Gets Fixed Faster",
    excerpt: "The details that let a technician solve your problem on the first pass, instead of the third round of back-and-forth.",
    readTime: 5,
    level: "Beginner",
    body: [
      { h: "Describe the problem, not your theory about it", p: "\"The printer won't print\" is more useful than \"I think the network is down,\" even if you suspect the network. Let the technician diagnose the cause." },
      { h: "Include the exact error message", p: "A screenshot or the exact text of an error message saves a technician from having to reproduce the problem just to see what you saw." },
      { h: "Say what you already tried", p: "If you already restarted the device or cleared the cache, say so. It stops the ticket from bouncing back with the first thing you already ruled out." },
      { h: "Note when it started and how often it happens", p: "Timing is often the clue that narrows the problem down — \"every time I open the app\" points to a very different cause than \"once, this morning.\"" },
      { h: "Flag the impact", p: "One sentence on how it affects your work helps support teams prioritize correctly." },
    ],
  },
  {
    id: "choosing-password-manager",
    category: "Software & Tools",
    title: "Choosing the Right Password Manager for Your Team",
    excerpt: "What actually matters when comparing password managers for a small team, beyond the marketing page.",
    readTime: 6,
    level: "Beginner",
    body: [
      { h: "Shared vaults, not shared passwords", p: "The core feature you're buying is the ability to share a login with a teammate without ever revealing the plaintext password to them." },
      { h: "Look for real admin controls", p: "Confirm the tool can deprovision a departing user and rotate shared credentials in one step, not several manual ones." },
      { h: "Check where encryption actually happens", p: "Look for tools that encrypt data on your device before it ever reaches their servers, so even the provider can't read your vault." },
      { h: "Don't ignore the recovery story", p: "Ask what happens if someone forgets their master password. No recovery path is safe but brittle; a weak one defeats the point." },
      { h: "Trial it with real workflows", p: "Try the browser extension, the mobile app, and a shared-folder scenario before committing." },
    ],
  },
  {
    id: "windows-update-errors",
    category: "Windows",
    title: "Understanding Windows Update Errors and How to Fix Them",
    excerpt: "The handful of causes behind most failed Windows updates, and the order to check them in.",
    readTime: 7,
    level: "Intermediate",
    body: [
      { h: "Most failures are one of three things", p: "A stuck update cache, insufficient disk space, or a corrupted system file. Working through these three in order resolves the majority of update errors." },
      { h: "Clear the update cache first", p: "Stop the Windows Update service, clear the SoftwareDistribution folder, then restart the service. This forces a fresh download instead of retrying a corrupted file." },
      { h: "Check available disk space", p: "Major updates can need several gigabytes of free space to stage. A nearly full drive is often the entire cause." },
      { h: "Run the built-in troubleshooter", p: "Windows' own Update Troubleshooter automatically detects and fixes the most common configuration issues." },
      { h: "Repair system files as a last step", p: "Run sfc /scannow followed by DISM /Online /Cleanup-Image /RestoreHealth to repair the underlying files an update depends on." },
    ],
  },
  {
    id: "remote-work-security-checklist",
    category: "IT Support",
    title: "Remote Work IT Checklist: Securing a Home Office Setup",
    excerpt: "The practical, non-paranoid checklist for making a home office setup reasonably secure.",
    readTime: 6,
    level: "Intermediate",
    body: [
      { h: "Start with the router", p: "Change the default admin password, confirm WPA3 or WPA2 encryption is enabled, and keep the router's firmware updated." },
      { h: "Separate work from personal traffic", p: "Where possible, keep work devices off the same network as smart home devices and guest traffic." },
      { h: "Keep the VPN and updates non-optional", p: "Disabling them for convenience is one of the most common ways home setups become the weak link." },
      { h: "Lock the physical device too", p: "Full-disk encryption and a short auto-lock timeout matter more at home, since a lost laptop has no building security to fall back on." },
      { h: "Use a password manager and MFA everywhere", p: "Multi-factor authentication closes off the most common way stolen credentials turn into a breach." },
    ],
  },
];
